version: '3'

services:
  strapi:
    # specify Dockerfile path
    build: ./backend
    image: nursing-home-volunteer/backend
    restart: unless-stopped
    # .env file includes db name, db username and password
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: '${POSTGRES_DB}'
      DATABASE_USERNAME: '${POSTGRES_USER}'
      DATABASE_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    volumes:
      - ./backend/public/uploads:/usr/src/app/public/uploads

  postgres:
    image: postgres
    restart: unless-stopped
    # .env file includes db name, db username and password
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data

  frontend:
    # specify Dockerfile path
    build: ./frontend
    image: nursing-home-volunteer/frontend
    restart: unless-stopped
    ports:
      - '80:80'
