# The applications are deployed on a linux server using the nginx-proxy from:
# https://github.com/larsrickert/nginx-proxy
version: '3'

services:
  strapi:
    build: ./backend
    image: nursing-home-volunteer/backend
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: '${POSTGRES_DB}'
      DATABASE_USERNAME: '${POSTGRES_USER}'
      DATABASE_PASSWORD: '${POSTGRES_PASSWORD}'
      VIRTUAL_HOST: '${BACKEND_DOMAIN}'
      LETSENCRYPT_HOST: '${BACKEND_DOMAIN}'
    expose:
      - 1337
    depends_on:
      - postgres
    volumes:
      - ./docker-data/uploads:/usr/src/app/public/uploads

  postgres:
    image: postgres
    restart: always
    # .env file includes db name, db username and password
    env_file: .env
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_API_HOST: 'https://${BACKEND_DOMAIN}'
    image: nursing-home-volunteer/frontend
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: '${FRONTEND_DOMAIN}'
      LETSENCRYPT_HOST: '${FRONTEND_DOMAIN}'

networks:
  default:
    name: nginx-proxy
    external: true
